#ifndef RAYMARCH_APP_COMMON_HPP
#define RAYMARCH_APP_COMMON_HPP

#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

enum class MButton {
    LEFT = GLFW_MOUSE_BUTTON_LEFT,
    RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
    MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE
};

enum class Action {
    PRESS = GLFW_PRESS,
    RELEASE = GLFW_RELEASE,
    REPEAT = GLFW_REPEAT
};

#endif//RAYMARCH_APP_COMMON_HPP
